### ISSUE TITLE
login still not possible

### ISSUE THREAD

**Issue by kevin-weiss** [tnychn/instascrape#17]
Hi there, thanks for fixing #2. I can finally get past this point. Unfortunately I cannot login yet. I tried using sms and google auth for 2fa and even disabled it for testing, but I still have to choose between sms and email which both results in an error. I got a notification of _unusual login behaviour_ in app and browser, which I confirmed but it didn't change anything. 

## 2fa via sms

```python 
# instascrape -d login 
    Saved Cookies 
(1) + [Login New Account] 
(1-1)choice> 1 
Username: myaccount 
Password: 
- Logging in... 
    getting cookie by username and password 
    login response data -> {'message': '', 'two_factor_required': True, 'two_factor_info': {'username': 'myaccount', 'sms_two_factor_on': True, 'totp_two_factor_on': False, 'obfuscated_phone_number': 'YYYY', 'two_factor_identifier': 'asdf', 'show_messenger_code_option': False, 'show_new_login_screen': True, 'show_trusted_device_option': True, 'should_opt_in_trusted_device_option': True, 'pending_trusted_notification': False, 'sms_not_allowed_reason': None, 'phone_verification_settings': {'max_sms_count': 2, 'resend_sms_delay_sec': 60, 'robocall_count_down_time_sec': 30, 'robocall_after_max_sms': True}}, 'phone_verification_settings': {'max_sms_count': 2, 'resend_sms_delay_sec': 60, 'robocall_count_down_time_sec': 30, 'robocall_after_max_sms': True}, 'status': 'fail', 'error_type': 'two_factor_required'} 
- [2FA] Security code sent to phone number: XXXX YYYY 
[2FA] Security Code: 123456 
    {'message': 'This code is no longer valid. Please request a new one.', 'status': 'fail', 'error_type': 'invalid_nonce'} 
 ERROR  LoginError: Failed to log into Instagram. (message: 'This code is no longer valid. Please request a new one.') 
      File "/home/kelso/Downloads/git/instascrape/isenv/lib/python3.9/site-packages/instascraper-2.0.4-py3.9.egg/instascrape/commands/__init__.py", line 123, in error_catcher 
    yield 
  File "/home/kelso/Downloads/git/instascrape/isenv/lib/python3.9/site-packages/instascraper-2.0.4-py3.9.egg/instascrape/commands/login.py", line 71, in login_handler 
    insta.two_factor_login(code) 
  File "/home/kelso/Downloads/git/instascrape/isenv/lib/python3.9/site-packages/instascraper-2.0.4-py3.9.egg/instascrape/instascrape.py", line 151, in two_factor_login 
    raise LoginError(data.get("message") or "incorrect security code") 
✖ LoginError: Failed to log into Instagram. (message: 'This code is no longer valid. Please request a new one.') 
``` 

## 2fa via sms and totp 
```python 
instascrape -d login 
    Saved Cookies 
    (1) + [Login New Account] 
    (1-1)choice> 1 
    Username: myaccount 
    Password: 
    - Logging in... 
    -     getting cookie by username and password 
    -     login response data -> {'message': '', 'two_factor_required': True, 'two_factor_info': {'username': 'myaccount', 'sms_two_factor_on': True, 'totp_two_factor_on': True, 'obfuscated_phone_number': 'YYYY', 'two_factor_identifier': 'asdf', 'show_messenger_code_option': False, 'show_new_login_screen': True, 'show_trusted_device_option': True, 'should_opt_in_trusted_device_option': True, 'pending_trusted_notification': False, 'sms_not_allowed_reason': None, 'phone_verification_settings': {'max_sms_count': 2, 'resend_sms_delay_sec': 60, 'robocall_count_down_time_sec': 30, 'robocall_after_max_sms': True}}, 'phone_verification_settings': {'max_sms_count': 2, 'resend_sms_delay_sec': 60, 'robocall_count_down_time_sec': 30, 'robocall_after_max_sms': True}, 'status': 'fail', 'error_type': 'two_factor_required'} 
    - - [2FA] Security code sent to phone number: XXXX YYYY 
    - [2FA] Security Code: 123456 
    -     {'message': 'This code is no longer valid. Please request a new one.', 'status': 'fail', 'error_type': 'invalid_nonce'} 
    -  ERROR  LoginError: Failed to log into Instagram. (message: 'This code is no longer valid. Please request a new one.') 
    -       File "/home/kelso/Downloads/git/instascrape/isenv/lib/python3.9/site-packages/instascraper-2.0.4-py3.9.egg/instascrape/commands/__init__.py", line 123, in error_catcher 
    -     yield 
    -   File "/home/kelso/Downloads/git/instascrape/isenv/lib/python3.9/site-packages/instascraper-2.0.4-py3.9.egg/instascrape/commands/login.py", line 71, in login_handler 
    -     insta.two_factor_login(code) 
    -   File "/home/kelso/Downloads/git/instascrape/isenv/lib/python3.9/site-packages/instascraper-2.0.4-py3.9.egg/instascrape/instascrape.py", line 151, in two_factor_login 
    -     raise LoginError(data.get("message") or "incorrect security code") 
  - â LoginError: Failed to log into Instagram. (message: 'This code is no longer valid. Please request a new one.') 
``` 

## 2fa disabled, chose email 
```python 
instascrape -d login 
    Saved Cookies 
(1) + [Login New Account] 
(1-1)choice> 1 
Username: myaccount 
Password: 
- Logging in... 
    getting cookie by username and password 
    login response data -> {'message': 'checkpoint_required', 'checkpoint_url': '/challenge/asdf/jkl/', 'lock': False, 'flow_render_type': 0, 'status': 'fail'} 
- [Checkpoint] Please verify your account at '/challenge/asdf/jkl/' 
ⓘ Note that if there is no phone number bound to this account, choosing SMS will fail the challenge. 
[Checkpoint] (0)-SMS (1)-Email (0|1)> 1 
 ERROR  JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
      File "/home/kelso/Downloads/git/instascrape/isenv/bin/instascrape", line 33, in <module> 
    sys.exit(load_entry_point('instascraper==2.0.4', 'console_scripts', 'instascrape')()) 
  File "/home/kelso/Downloads/git/instascrape/isenv/lib/python3.9/site-packages/instascraper-2.0.4-py3.9.egg/instascrape/__main__.py", line 196, in main 
    args.func(**vars(args)) 
  File "/home/kelso/Downloads/git/instascrape/isenv/lib/python3.9/site-packages/instascraper-2.0.4-py3.9.egg/instascrape/commands/login.py", line 78, in login_handler 
    auth = insta.checkpoint_challenge_login(int(mode)) 
  File "/home/kelso/Downloads/git/instascrape/isenv/lib/python3.9/site-packages/instascraper-2.0.4-py3.9.egg/instascrape/instascrape.py", line 178, in checkpoint_challenge_login 
    self.logger.debug(resp.json()) 
  File "/home/kelso/Downloads/git/instascrape/isenv/lib/python3.9/site-packages/requests-2.25.0-py3.9.egg/requests/models.py", line 900, in json 
    return complexjson.loads(self.text, **kwargs) 
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads 
    return _default_decoder.decode(s) 
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode 
    obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode 
    raise JSONDecodeError("Expecting value", s, err.value) from None 
Traceback (most recent call last): 
  File "/home/kelso/Downloads/git/instascrape/isenv/bin/instascrape", line 33, in <module> 
    sys.exit(load_entry_point('instascraper==2.0.4', 'console_scripts', 'instascrape')()) 
  File "/home/kelso/Downloads/git/instascrape/isenv/lib/python3.9/site-packages/instascraper-2.0.4-py3.9.egg/instascrape/__main__.py", line 196, in main 
  File "/home/kelso/Downloads/git/instascrape/isenv/lib/python3.9/site-packages/instascraper-2.0.4-py3.9.egg/instascrape/commands/login.py", line 78, in login_handler 
  File "/home/kelso/Downloads/git/instascrape/isenv/lib/python3.9/site-packages/instascraper-2.0.4-py3.9.egg/instascrape/instascrape.py", line 178, in checkpoint_challenge_login 
  File "/home/kelso/Downloads/git/instascrape/isenv/lib/python3.9/site-packages/requests-2.25.0-py3.9.egg/requests/models.py", line 900, in json 
    return complexjson.loads(self.text, **kwargs) 
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads 
    return _default_decoder.decode(s) 
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode 
    obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode 
    raise JSONDecodeError("Expecting value", s, err.value) from None 
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
```

**Comment by Gahamelas** [comment]
When I choose email, I get an error: ```
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by kevin-weiss** [comment]
I could now successfully log in, although I had to temprorarily disable 2FA. Both Google Auth and SMS verification gave me this error:

```
LoginError: Failed to log into Instagram. (message: 'This code is no longer valid. Please request a new one.')
```
