### ISSUE TITLE
login not possible (csrftoken)

### ISSUE THREAD

**Issue by kevin-weiss** [tnychn/instascrape#2]
Unfortunately I cannot login:

```bash
Traceback (most recent call last):
  File $HOME/.virtualenvs/insta/bin/instascrape", line 11, in <module>
    load_entry_point('instascrape-ax==1.1.1', 'console_scripts', 'instascrape')()
  File "$HOME/.virtualenvs/insta/lib/python3.7/site-packages/instascrape_ax-1.1.1-py3.7.egg/instascrape/cli.py", line 649, in main
  File "$HOME/.virtualenvs/insta/lib/python3.7/site-packages/instascrape_ax-1.1.1-py3.7.egg/instascrape/cli.py", line 217, in login
  File "$HOME/.virtualenvs/insta/lib/python3.7/site-packages/instascrape_ax-1.1.1-py3.7.egg/instascrape/instascraper.py", line 118, in login
KeyError: 'csrftoken'
```
The problem appears also in v1.1.0. I tried turning off 2FA, but it makes no difference.

**Comment by a1phat0ny** [comment]
Please upgrade **InstaScrape** to **v1.1.1** and try logging in with `instascrape --debug login`. This will print out some debug messages (including the http response of your login). They are helpful for me to think what caused the error!

Remember to censor your credentials!
Thanks!

**Comment by kevin-weiss** [comment]
```bash
instascrape --debug login
    DEBUG: loading object from $HOME/.instascrape/insta.pkl...
    DEBUG: $HOME/.instascrape/insta.pkl pickle file not found.

    Choose Account

(1) + Login New Account

choice> 1
Username: $USER
Password:
    DEBUG: Logging in...
    DEBUG: trying to load cookie from $HOME/.instascrape/accounts/$USER.cookie...
    DEBUG: cookie file for $USER not found
    DEBUG: getting cookie by username and password
<instascrape.instascraper.InstaScraper object at 0x7f2b9e768e10>
Traceback (most recent call last):
  File "$HOME/.virtualenvs/insta/bin/instascrape", line 11, in <module>
    load_entry_point('instascrape-ax==1.1.1', 'console_scripts', 'instascrape')()
  File "$HOME/.virtualenvs/insta/lib/python3.7/site-packages/instascrape_ax-1.1.1-py3.7.egg/instascrape/cli.py", line 649, in main
  File "$HOME/.virtualenvs/insta/lib/python3.7/site-packages/instascrape_ax-1.1.1-py3.7.egg/instascrape/cli.py", line 217, in login
  File "$HOME/.virtualenvs/insta/lib/python3.7/site-packages/instascrape_ax-1.1.1-py3.7.egg/instascrape/instascraper.py", line 120, in login
KeyError: 'csrftoken'
```

**Comment by yessure** [comment]
I got the same issue

**Comment by hilmiazizi** [comment]
same issue here

**Comment by kh3rad** [comment]
same issue here
```
[root@s2 ~]# instascrape --debug login -u saeed
    DEBUG: loading object from /root/.instascrape/insta.pkl...
    DEBUG: /root/.instascrape/insta.pkl pickle file not found.
* Cookie file does not exist yet. Getting credentials...
Password: 
    DEBUG: Logging in...
    DEBUG: trying to load cookie from /root/.instascrape/accounts/saeed.cookie...
    DEBUG: cookie file for saeed not found
    DEBUG: getting cookie by username and password
Traceback (most recent call last):
  File "/usr/local/bin/instascrape", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instascrape/cli.py", line 651, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/instascrape/cli.py", line 217, in login
    insta.login()  # keep the logged in state and store it in the pickle
  File "/usr/local/lib/python3.7/site-packages/instascrape/instascraper.py", line 118, in login
    csrftoken = self._session.cookies.get_dict()["csrftoken"]
KeyError: 'csrftoken'
```

**Comment by a1phat0ny** [comment]
Instascrape v2.0.0 has just released. Please try it out, and let me know if the problem persists.
Thanks!

**Comment by kevin-weiss** [comment]
I finally managed to test it with v2.0.1 and it seems that the problem persists:

```bash
instascrape --debug login

    Saved Cookies

(1) + [Login New Account]

(1-1)choice> 1
Username: $USER
Password:
- Logging in...
    getting cookie by username and password
 ERROR  KeyError: 'csrftoken'
      File "$HOME/.virtualenvs/insta/bin/instascrape", line 10, in <module>
    sys.exit(main())
  File "$HOME/.virtualenvs/insta/lib/python3.7/site-packages/instascrape/__main__.py", line 196, in main
    args.func(**vars(args))
  File "$HOME/.virtualenvs/insta/lib/python3.7/site-packages/instascrape/commands/login.py", line 65, in login_handler
    insta.login(username, password, load_cookie(cookie_name) if cookie_name else None)
  File "$HOME/.virtualenvs/insta/lib/python3.7/site-packages/instascrape/instascrape.py", line 112, in login
    session.headers.update({"X-CSRFToken": session.cookies.get_dict()["csrftoken"]})

Traceback (most recent call last):
  File "$HOME/.virtualenvs/insta/bin/instascrape", line 10, in <module>
    sys.exit(main())
  File "$HOME/.virtualenvs/insta/lib/python3.7/site-packages/instascrape/__main__.py", line 196, in main
    args.func(**vars(args))
  File "$HOME/.virtualenvs/insta/lib/python3.7/site-packages/instascrape/commands/login.py", line 65, in login_handler
    insta.login(username, password, load_cookie(cookie_name) if cookie_name else None)
  File "$HOME/.virtualenvs/insta/lib/python3.7/site-packages/instascrape/instascrape.py", line 112, in login
    session.headers.update({"X-CSRFToken": session.cookies.get_dict()["csrftoken"]})
KeyError: 'csrftoken'
```

**Comment by a1phat0ny** [comment]
It seems that the following lines of code are causing the problem.

https://github.com/a1phat0ny/instascrape/blob/92ba6e073790c0475bb51d5ce8d03b2f97cc6c2d/instascrape/instascrape.py#L110-L112

Since I failed to reproduce the error, I'm not sure if my persumption is correct.
I guess we should get the value of the `csrftoken` cookie from the response, rather than the cookie jar of the session itself. So I changed the code into the following lines:

https://github.com/a1phat0ny/instascrape/blob/ff2127d93bb0a0799bd45c33a8c3a9e01e046aa8/instascrape/instascrape.py#L110-L112

Upgrade `instascrape` to the lastest GitHub commit using pip:
`$ pip install git+https://github.com/a1phat0ny/instascrape@master --upgrade`
Please test it out and let me know if the problem persists.

**Comment by kevin-weiss** [comment]
I just tested it with the current version. The error is basically the same, only the second last line differs: 

```bash
    session.headers.update({"X-CSRFToken": req.cookies.get_dict()["csrftoken"]})
KeyError: 'csrftoken'
```

**Comment by terpelajar** [comment]
`ERROR  HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/users/21788670033/info/
      File "/data/data/com.termux/files/usr/bin/instascrape", line 11, in <module>
    load_entry_point('instascraper==2.0.1', 'console_scripts', 'instascrape')()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instascrape/__main__.py", line 196, in main
    args.func(**vars(args))
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instascrape/commands/login.py", line 65, in login_handler
    insta.login(username, password, load_cookie(cookie_name) if cookie_name else None)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instascrape/instascrape.py", line 139, in login
    self._post_login()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instascrape/instascrape.py", line 207, in _post_login
    self.my_username = get_username_from_userid(self.my_user_id)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instascrape/utils.py", line 60, in get_username_from_userid
    resp.raise_for_status()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/instascrape", line 11, in <module>
    load_entry_point('instascraper==2.0.1', 'console_scripts', 'instascrape')()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instascrape/__main__.py", line 196, in main
    args.func(**vars(args))
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instascrape/commands/login.py", line 65, in login_handler
    insta.login(username, password, load_cookie(cookie_name) if cookie_name else None)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instascrape/instascrape.py", line 139, in login
    self._post_login()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instascrape/instascrape.py", line 207, in _post_login
    self.my_username = get_username_from_userid(self.my_user_id)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instascrape/utils.py", line 60, in get_username_from_userid
    resp.raise_for_status()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/users/21788670033/info/`

Help

**Comment by beratsumay** [comment]
any updates ?

**Comment by a1phat0ny** [comment]
@terpelajar [Instascrape v2.0.2](https://github.com/a1phat0ny/instascrape/releases/tag/v2.0.2) has just been released. This release introduces a fix to this problem. Please upgrade your `instascrape`. Thanks!
`$ pip install instascraper --upgrade`

**Comment by kevin-weiss** [comment]
```bash
- Logging in...
    getting cookie by username and password
    failed to find 'csrftoken' in first attempt, using endpoint '/web/__mid'
✖ cannot find 'csrftoken' from cookies
```

**Comment by a1phat0ny** [comment]
I have no idea about how to fix this problem too... since I cannot reproduce this error. Maybe you should check the logfile at `~/.instascrape/instascrape.log` and see what's the JSON response from Instagram tells you.

My logs of the `login` action:
```
───────┬────────────────────────────────────────────────────────────────────────
       │ File: /Users/tony/.instascrape/instascrape.log
───────┼────────────────────────────────────────────────────────────────────────
   1   │ [17:35:29] [MainThread/INFO] (file='instascrape.py' line=87 func='login
       │ '): Logging in...
   2   │ [17:35:29] [MainThread/DEBUG] (file='instascrape.py' line=99 func='logi
       │ n'): getting cookie by username and password
   3   │ [17:35:32] [MainThread/DEBUG] (file='instascrape.py' line=115 func='log
       │ in'): login response data -> {'authenticated': True, 'user': True, 'use
       │ rId': 'censored', 'oneTapPrompt': False, 'fr': 'censored', 'status': 'ok'}
   4   │ [17:35:32] [MainThread/DEBUG] (file='instascrape.py' line=198 func='_po
       │ st_login'): Cookie: <RequestsCookieJar[<Cookie csrftoken=censored for .instagram.com/>,
       | <Cookie ds_user_id=censored for .instagram.com/>, <Cookie mid=censored for .in
       │ stagram.com/>, <Cookie rur=censored for .instagram.com/>, <Cookie sessionid=
       │ censored for .instagram.com/>, <Cookie shbid=censored for .instagram.com/>, <Cookie 
       | shbts=censored for .instagram.com/>]>
   5   │ [17:35:32] [MainThread/INFO] (file='instascrape.py' line=203 func='_pos
       │ t_login'): Logged in -> @censored (censored)
───────┴────────────────────────────────────────────────────────────────────────
```

**Comment by Gahamelas** [comment]
Same problem. Has somebody figured out how to fix it? Otherwise, I can't use this tool at all.

**Comment by a1phat0ny** [comment]
Mmmm...maybe I should try reading how other projects implement the login logic...

**Comment by DeiRep** [comment]
> Mmmm...maybe I should try reading how other projects implement the login logic...

Does it work on your side or is it just us?

**Comment by a1phat0ny** [comment]
It works fine on my side... that's why it's hard for me to debug this issue as I can't reproduce the error on my machine.

**Comment by DeiRep** [comment]
> It works fine on my side... that's why it's hard for me to debug this issue as I can't reproduce the error on my machine.

Is there something I can provide you with to help reproduce the error?
Also, what are you running? There may be some missing dependencies or something like that on our side...

**Comment by DeiRep** [comment]
> It works fine on my side... that's why it's hard for me to debug this issue as I can't reproduce the error on my machine.

Ok, I'm tried to use this tool on my local machine running Linux Mint, no errors were faced. Logged in successfully.
But the error persists on my remote machine running Linux Debian 9.

I also have another question since now I'm able to generate cookies on my local machine, where do I get the cookie file on my local machine to (and where) put it on my remote machine?

**Comment by a1phat0ny** [comment]
The cookies are stored at `~/.instascrape/cookies/{username}.cookie`. You can copy the file to the same path on your remote machine.

**Comment by DeiRep** [comment]
> The cookies are stored at `~/.instascrape/cookies/{username}.cookie`. You can copy the file to the same path on your remote machine.

Ty, do I need to copy the `instasession.pickle` aswell?

**Comment by a1phat0ny** [comment]
No I don’t think it’s needed as it would cause the same session exists in two different machines.

**Comment by DeiRep** [comment]
Hey, sorry to bother and offtop, is there any way to contact you? Like Telegram or email?

**Comment by a1phat0ny** [comment]
https://t.me/tnychn

**Comment by air-10** [comment]
Login not possible here too, got this on Mojave `Traceback (most recent call last):
  File "/opt/miniconda3/bin/instascrape", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/lib/python3.7/site-packages/instascrape/__main__.py", line 196, in main
    args.func(**vars(args))
  File "/opt/miniconda3/lib/python3.7/site-packages/instascrape/commands/login.py", line 65, in login_handler
    insta.login(username, password, load_cookie(cookie_name) if cookie_name else None)
  File "/opt/miniconda3/lib/python3.7/site-packages/instascrape/instascrape.py", line 114, in login
    data = resp.json()
  File "/opt/miniconda3/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/miniconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by mvajid** [comment]
Also cannot login..

Traceback (most recent call last):
  File "/home/mohamad/.local/bin/instascrape", line 8, in <module>
    sys.exit(main())
  File "/home/mohamad/.local/lib/python3.8/site-packages/instascrape/__main__.py", line 196, in main
    args.func(**vars(args))
  File "/home/mohamad/.local/lib/python3.8/site-packages/instascrape/commands/login.py", line 65, in login_handler
    insta.login(username, password, load_cookie(cookie_name) if cookie_name else None)
  File "/home/mohamad/.local/lib/python3.8/site-packages/instascrape/instascrape.py", line 114, in login
    data = resp.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mvajid** [comment]
(1-1)choice> 1
Username: **********
Password: 
- Logging in...
    getting cookie by username and password
 ERROR  JSONDecodeError: Expecting value: line 1 column 1 (char 0)
      File "/home/mohamad/.local/bin/instascrape", line 8, in <module>
    sys.exit(main())
  File "/home/mohamad/.local/lib/python3.8/site-packages/instascrape/__main__.py", line 196, in main
    args.func(**vars(args))
  File "/home/mohamad/.local/lib/python3.8/site-packages/instascrape/commands/login.py", line 65, in login_handler
    insta.login(username, password, load_cookie(cookie_name) if cookie_name else None)
  File "/home/mohamad/.local/lib/python3.8/site-packages/instascrape/instascrape.py", line 114, in login
    data = resp.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())

**Comment by air-10** [comment]
I came up with a good workaround to save your saved posts without faulty instascrape:
1) add a chrome extention called "Save All Resources"
2) open your saved tab in a chrome browser (click on your userpic - then Saved) and scroll down all of your saved posts. The server cuts down every 2000 pics or so, so be patient and give it 10 min if the page refuses to scroll deeper at some point. 
3) when you reach the end of the page open devtools, click ResourcesSaver tab there
4) leave all the settings as it is and click download
5) voila, you now got a zip file with all your saved posts
6) search there for ".jpg" with your file browser and move all of them in one folder
 
hope that helps. Worked for me.

**Comment by Gahamelas** [comment]
I wouldn't trust this air-10 (it has "assholishness" written all over it.

**Comment by jayu27-sudo** [comment]
# [@kevin-weiss also not```
# __``
```

**Comment by kevin-weiss** [comment]
[This](https://gist.github.com/kevin-weiss/4bc0051962d5141145782a1f27fde4a2) could be a possible solution. I fiddled a bit with beautifulsoup to get the csrftoken. It is quick and dirty by now, but it sure can be optimized.

**Comment by kevin-weiss** [comment]
I tested my approach in [this fork](https://github.com/kevin-weiss/instascrape). But just adding the csrf header doesn't seem to resolve the issue. Sending the login payload data resulted in an error 400. I guess I've got to dig a little deeper into it.

**Comment by Arrvindraa** [comment]
Traceback (most recent call last):
  File "crack.py", line 108, in <module>
    sess = instabrute.Login(password)
  File "crack.py", line 83, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'                                                       Pls help me guys😢😢😢😢

**Comment by harshditu08** [comment]
> @terpelajar [Instascrape v2.0.2](https://github.com/a1phat0ny/instascrape/releases/tag/v2.0.2) has just been released. This release introduces a fix to this problem. Please upgrade your `instascrape`. Thanks!
> `$ pip install instascraper --upgrade`

Traceback (most recent call last):                File "crack.py", line 108, in <module>
    sess = instabrute.Login(password)
  File "crack.py", line 83, in Login                sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})                    KeyError: 'csrftoken'

It's showing like this 😭😭😭Even i used this comment  `$ pip install instascraper --upgrade

**Comment by 2025-sagar-1** [comment]
Traceback (most recent call last):
  File "hackinsta.py", line 154, in <module>
    sess = instabrute.Login(password)
  File "hackinsta.py", line 118, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'.      Please help me

**Comment by 2025-sagar-1** [comment]
Traceback (most recent call last):
  File "hackinsta.py", line 154, in <module>
    sess = instabrute.Login(password)
  File "hackinsta.py", line 118, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'.   Please help me

**Comment by 2025-sagar-1** [comment]
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the '/data/data/com.termux/files/usr/bin/python3 -m pip install --upgrade pip' command.
$ python hackinsta.py
Please enter a username: varun_sagar_2_17
[*] 1315 Passwords loads successfully
[*] Do you want to use proxy (y/n): n
[*] Please add delay between the bruteforce action (in seconds): 1

Traceback (most recent call last):
  File "hackinsta.py", line 154, in <module>
    sess = instabrute.Login(password)
  File "hackinsta.py", line 118, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'. Please help me please 🙏🙏🥺

**Comment by harshditu08** [comment]
Ok bro !! But plzzz teach me or show me ur article that how real hacking
works on Instagram.....I want learn coz my sister is getting some backmails
on her private photos by her Bf 😭😭😭 So plzzz tell me the real hacking
workings

**Comment by 2025-sagar-1** [comment]
sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})

**Comment by 2025-sagar-1** [comment]
Traceback (most recent call last):
  File "hackinsta.py", line 154, in <module>
    sess = instabrute.Login(password)
  File "hackinsta.py", line 118, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'
$.  Please help me please 🙏🥺🙏

**Comment by 1232154pp4749687** [comment]
pleease fix

**Comment by tnychn** [comment]
@1232154pp4749687
Already attempted to fix this issue in c006b25485c3f00c85f546aae17d107ef613583b.
Please upgrade **instascrape** to **v2.0.4** by using `pip3 install instascraper --upgrade`.
If you still have any problem logging in, please refer to #17.

**Comment by NOBHACKER120** [comment]
Hi issue in instascrape (key error csrftoken)
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/alkrinsta/alkrinsta.py", line 146, in <module>
    sess = instabrute.Login(password)
  File "/data/data/com.termux/files/home/alkrinsta/alkrinsta.py", line 110, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'

**Comment by Sonya1122** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/alkrinsta/alkrinsta.py", line 146, in <module>
    sess = instabrute.Login(password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/alkrinsta/alkrinsta.py", line 110, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'csrftoken'




Please help
