### ISSUE TITLE
Getting key error, csrftoken in line 114 . help

### ISSUE THREAD

**Issue by PirATesofArabian** [tnychn/instascrape#32]

**Comment by NOBHACKER120** [comment]
Hi issue in instascrape (key error csrftoken)
Traceback (most recent call last):
File "/data/data/com.termux/files/home/alkrinsta/alkrinsta.py", line 146, in
sess = instabrute.Login(password)
File "/data/data/com.termux/files/home/alkrinsta/alkrinsta.py", line 110, in Login
sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'

Help
