### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sa713** [tnychn/instascrape#35]
use example and get error

Traceback (most recent call last):
  File "./sc.py", line 7, in <module>
    posts = insta.profile("sensual_ladies").timeline_posts()
  File "/usr/local/lib/python3.7/site-packages/instascrape/instascrape.py", line 346, in profile
    return Profile.from_username(self, name)
  File "/usr/local/lib/python3.7/site-packages/instascrape/structures.py", line 684, in from_username
    profile._obtain_full_data()
  File "/usr/local/lib/python3.7/site-packages/instascrape/structures.py", line 696, in _obtain_full_data
    self._full_data = self._insta._fetch_json_data(PROFILE_URL.format(username=self.username))["user"]
  File "/usr/local/lib/python3.7/site-packages/instascrape/instascrape.py", line 259, in _fetch_json_data
    data = resp.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by 89z** [comment]
Same error

**Comment by E3Negocios** [comment]
Same error

**Comment by olivertwistor** [comment]
Me too.
